// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
/*      case TargetPlatform.iOS:
        return ios; */
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXZaeVg5m1FK1FqT8_FlaP7i8SawY5Cpw',
    appId: '1:978858791861:web:2516eec483abf30a9dbffc',
    messagingSenderId: '978858791861',
    projectId: 'app-fn-a25e1',
    authDomain: 'app-fn-a25e1.firebaseapp.com',
    storageBucket: 'app-fn-a25e1.firebasestorage.app',
    measurementId: 'G-R63RC7L085',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnxNkyxohVHjpEkhJhwf-JkNmsLaAym1U',
    appId: '1:978858791861:android:50166d44060a1d239dbffc',
    messagingSenderId: '978858791861',
    projectId: 'app-fn-a25e1',
    storageBucket: 'app-fn-a25e1.firebasestorage.app',
  );

/*  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX6Xww_U2Xlyl2SIzeq8zomdywYJLWAAQ',
    appId: '1:978858791861:ios:efc95505c035b23b9dbffc',
    messagingSenderId: '978858791861',
    projectId: 'app-fn-a25e1',
    storageBucket: 'app-fn-a25e1.firebasestorage.app',
    iosBundleId: 'com.example.appGastos',
  );  */

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAX6Xww_U2Xlyl2SIzeq8zomdywYJLWAAQ',
    appId: '1:978858791861:ios:efc95505c035b23b9dbffc',
    messagingSenderId: '978858791861',
    projectId: 'app-fn-a25e1',
    storageBucket: 'app-fn-a25e1.firebasestorage.app',
    iosBundleId: 'com.example.appGastos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXZaeVg5m1FK1FqT8_FlaP7i8SawY5Cpw',
    appId: '1:978858791861:web:ac57458efe357bb09dbffc',
    messagingSenderId: '978858791861',
    projectId: 'app-fn-a25e1',
    authDomain: 'app-fn-a25e1.firebaseapp.com',
    storageBucket: 'app-fn-a25e1.firebasestorage.app',
    measurementId: 'G-8QSG5C4S7M',
  );

}